# -*- coding: utf-8 -*-
"""Embedding_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xj27g3qNIvN1iy-e_HG5HR9FIHdR7Kwd

# Installing Libraries and Mount Drive
"""

! pip install torch transformers h5py pandas tqdm pillow torchvision torchxrayvision

from google.colab import drive

drive.mount('/content/drive')

"""# Reports

## Import Libraries
"""

import re
import torch
import h5py
import pandas as pd
import numpy as np
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModel

"""## Load *report_df (note_id, text_description)*"""

csv_path = "/content/drive/MyDrive/MIMIC_Data/to_preload.csv"
tsv_path = "/content/drive/MyDrive/MIMIC_Data/to_preload_notes.tsv"

import pandas as pd

# Load CSV (image_path + note_id)
cxr_df = pd.read_csv(csv_path)

# Load TSV (note_id + report text)
report_df = pd.read_csv(tsv_path, sep="\t", encoding="latin-1")

print(cxr_df.head())
print(report_df.head())

report_df.columns

"""## Preprocess text"""

note_ids = report_df['note_id'].astype('str').tolist()
reports = report_df['text_description'].tolist()

assert len(note_ids) == len(reports)

len(note_ids)

def clean_report(text):
    """
    Minimal cleaning.
    Keeps negation and medical terms intact.
    """
    text = str(text)
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def extract_sections(report):
    """
    Extract FINDINGS and IMPRESSION sections if present.
    Falls back to full report otherwise.
    """
    report_upper = report.upper()

    findings = ""
    impression = ""

    if "FINDINGS:" in report_upper:
        findings = report_upper.split("FINDINGS:")[1]
        if "IMPRESSION:" in findings:
            findings = findings.split("IMPRESSION:")[0]

    if "IMPRESSION:" in report_upper:
        impression = report_upper.split("IMPRESSION:")[1]

    combined = findings + " " + impression

    if combined.strip() == "":
        combined = report

    return clean_report(combined)

"""## Load RadBERT Model"""

MODEL_NAME = "zzxslp/RadBERT-RoBERTa-4m"
BATCH_SIZE = 16
MAX_LENGTH = 512

OUPUT_PATH = "report_embeddings.h5"
ID_COLUMN = "note_id"
TEXT_COLUMN = "text_description"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModel.from_pretrained(MODEL_NAME)
model.to(device)
model.eval()

all_embeddings = []
valid_ids = []

with torch.no_grad():
    for i in tqdm(range(0, len(reports), BATCH_SIZE)):

        batch_texts = reports[i:i+BATCH_SIZE]
        batch_ids = note_ids[i:i+BATCH_SIZE]  # FIXED

        processed = []
        kept_ids = []

        for nid, rpt in zip(batch_ids, batch_texts):
            try:
                rpt = extract_sections(rpt)
                processed.append(rpt)          # ONLY append report
                kept_ids.append(nid)           # append ID separately
            except:
                continue

        if len(processed) == 0:
            continue

        inputs = tokenizer(
            processed,
            padding=True,
            truncation=True,
            max_length=MAX_LENGTH,
            return_tensors="pt"
        )

        inputs = {k: v.to(device) for k, v in inputs.items()}

        outputs = model(**inputs)

        cls_embeddings = outputs.last_hidden_state[:, 0, :]
        cls_embeddings = torch.nn.functional.normalize(cls_embeddings, dim=-1)

        all_embeddings.append(cls_embeddings.cpu())
        valid_ids.extend(kept_ids)

# Concatenate
all_embeddings = torch.cat(all_embeddings, dim=0).numpy()

print("Final embedding shape:", all_embeddings.shape)
print("Total IDs:", len(valid_ids))



len(processed), len(valid_ids), len(all_embeddings)

len(all_embeddings)

"""## Storing to hdf5"""

with h5py.File(OUPUT_PATH, "w") as hdf:
    grp = hdf.create_group("report_embeddings")

    str_dtype = h5py.string_dtype(encoding='utf-8')

    grp.create_dataset(
        "note_ids",
        data=np.array(valid_ids, dtype=str_dtype)
    )

    grp.create_dataset(
        "embeddings",
        data=all_embeddings,
        compression="gzip"
    )

    # Metadata
    grp.attrs["model"] = MODEL_NAME
    grp.attrs["embedding_dim"] = all_embeddings.shape[1]

print("Saved embeddings to:", OUPUT_PATH)

from google.colab import files

files.download(OUPUT_PATH)

"""# CXRS

## Extracting split embeddings

### Install Libraries
"""

import os
import torch
import h5py
import pandas as pd
import numpy as np
from tqdm import tqdm
from PIL import Image
import torchvision.transforms as transforms
import torchxrayvision as xrv

"""### Load paths"""

CXR_PATHS = "/content/drive/MyDrive/MIMIC_Data/CXR/CXR_split1/split1_paths.txt"
MISSING_PATHS = "/content/drive/MyDrive/MIMIC_Data/CXR/CXR_split1/split1_failed_paths.txt"
CXR_ROOT1 = "/content/drive/MyDrive/MIMIC_Data/CXR/CXR_split1/files1/"
CXR_ROOT2 = "/content/drive/MyDrive/MIMIC_Data/CXR/CXR_split1/files3/"

"""#### Normal Flow"""

with open(CXR_PATHS, "r") as f:
  image_paths = [line.strip() for line in f if line.strip()]

dicom_ids = [path.split("/")[-1].split(".")[0] for path in image_paths ]

print("Total images:", len(image_paths))
print("Dicom ids:", len(dicom_ids))

assert len(image_paths) == len(dicom_ids)

CXR_paths = []
missing_rel_paths = []

for path in image_paths:
  final_path1 = os.path.join(CXR_ROOT1, path)
  final_path2 = os.path.join(CXR_ROOT2, path)

  if os.path.exists(final_path1):
    CXR_paths.append(final_path1)

  elif os.path.exists(final_path2):
    CXR_paths.append(final_path2)

  else:
    missing_rel_paths.append(path)

print("Valid CXRS:", len(CXR_paths))
print("Missing paths:", len(missing_rel_paths))

"""#### Failed paths"""

with open(MISSING_PATHS, 'r') as f:
  image_paths = [line.strip() for line in f if line.strip()]

image_paths = [cleaned.replace("\\", "/") for cleaned in image_paths]

dicom_ids = [path.split("/")[-1].split(".")[0] for path in image_paths ]

print("Total images:", len(image_paths))
print("Dicom ids:", len(dicom_ids))

assert len(image_paths) == len(dicom_ids)

CXR_paths = []
missing_rel_paths = []
BASE_ROOT = "/content/drive/MyDrive/MIMIC_Data/CXR_split1/"

for path in image_paths:
  final_path = os.path.join(BASE_ROOT, path)

  if os.path.exists(final_path):
    CXR_paths.append(final_path)
  else:
    missing_rel_paths.append(path)

print("Valid CXRS:", len(CXR_paths))
print("Missing paths:", len(missing_rel_paths))

"""### Image Preprocessing"""

import torch.nn.functional as F

def preprocess_image(path):

    # Load image as numpy array (grayscale)
    img = Image.open(path).convert("L")
    img = np.array(img)

    # Normalize using XRV (expects numpy)
    img = xrv.datasets.normalize(img, maxval=255)

    # Convert to torch tensor
    img = torch.tensor(img).unsqueeze(0)  # (1, H, W)

    # Resize to 224x224
    img = F.interpolate(
        img.unsqueeze(0),
        size=(224, 224),
        mode="bilinear",
        align_corners=False
    ).squeeze(0)

    return img

"""### Load DenseNet Model"""

BATCH_SIZE = 16
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

model = xrv.models.DenseNet(weights="densenet121-res224-all")
model = model.to(device)
model.eval()

all_embeddings = []
valid_ids = []
failed_ids = []
failed_paths = []

with torch.no_grad():
    for i in tqdm(range(0, len(CXR_paths), BATCH_SIZE)):

        batch_paths = CXR_paths[i: i+BATCH_SIZE]
        batch_ids = dicom_ids[i: i+BATCH_SIZE]

        images = []
        kept_ids = []

        for dicom_id, path in zip(batch_ids, batch_paths):
            try:
                img = preprocess_image(path)
                images.append(img)
                kept_ids.append(dicom_id)
            except Exception as e:
                failed_paths.append(path)
                failed_ids.append(dicom_id)

        if len(images) == 0:
            continue

        images = torch.stack(images).to(device)

        features = model.features(images)
        pooled = torch.nn.functional.adaptive_avg_pool2d(features, (1,1))
        pooled = pooled.view(pooled.size(0), -1)
        pooled = torch.nn.functional.normalize(pooled, dim=-1)

        all_embeddings.append(pooled.cpu())
        valid_ids.extend(kept_ids)

all_embeddings = torch.cat(all_embeddings, dim=0).numpy()

print("\nFinal Embeddings size:", all_embeddings.shape)
print("Initial:", len(CXR_paths))
print("Valid:", len(valid_ids))
print("Failed:", len(failed_ids))

"""### Writing into HDF5 file"""

OUTPUT_HDF = "cxr_embeddings_split_1_failed.h5"

with h5py.File(OUTPUT_HDF, "w") as hdf:
    grp = hdf.create_group("cxr_embeddings_split_1_failed")

    str_dtype = h5py.string_dtype(encoding='utf-8')

    grp.create_dataset(
        "dicom_ids",
        data=np.array(valid_ids, dtype=str_dtype)
    )

    grp.create_dataset(
        "embeddings",
        data=all_embeddings,
        compression="gzip"
    )

    grp.attrs["model"] = "torchxrayvision/densenet121-res224-all"
    grp.attrs["embedding_dim"] = all_embeddings.shape[1]

print("Saved to:", OUTPUT_HDF)

from google.colab import files

files.download(OUTPUT_HDF)

"""### Writing embedding extraction status for each image"""

status_data = []
STATUS_CSV = "cxr_embedding_status_split1.csv"
for vid in valid_ids:
    status_data.append((vid, "valid"))

for fid in failed_ids:
    status_data.append((fid, "failed"))

status_df = pd.DataFrame(status_data, columns=["dicom_id", "status"])
status_df.to_csv(STATUS_CSV, index=False)

print(STATUS_CSV)

from google.colab import files

files.download(STATUS_CSV)

"""## Combining CXR Embeddings

### IMPORT LIBRARIES
"""

import h5py
import numpy as np

"""### SET PATH AND LOAD FILE"""

SPLIT1 = "/content/drive/MyDrive/MIMIC_Data/CXR/cxr_embeddings_split_1.h5"
SPLIT1_FAILED = "/content/drive/MyDrive/MIMIC_Data/CXR/cxr_embeddings_split_1_failed.h5"
SPLIT2 = "/content/drive/MyDrive/MIMIC_Data/CXR/cxr_embeddings_split_2.h5"
SPLIT3 = "/content/drive/MyDrive/MIMIC_Data/CXR/cxr_embeddings_split_3.h5"

FILES = [SPLIT1, SPLIT1_FAILED, SPLIT2, SPLIT3]

"""### EXTRACT *dicom_ids* AND *embeddings*"""

all_ids = []
all_embeddings = []

for fl in FILES:
    fname = fl.split("/")[-1].split(".")[0]
    print(f"Loading {fname}")

    with h5py.File(fl, "r") as f:
        ids = f[f"{fname}/dicom_ids"][:]
        emb = f[f"{fname}/embeddings"][:]

    # Decode byte strings if necessary
    ids = [i.decode() if isinstance(i, bytes) else i for i in ids]

    print(f"  Shape: {emb.shape}")

    all_ids.extend(ids)
    all_embeddings.append(emb)

# Stack embeddings
all_embeddings = np.vstack(all_embeddings)

print("\nTotal merged shape:", all_embeddings.shape)
print("Total IDs:", len(all_ids))

"""### Duplicate Check"""

print("Unique IDs:", len(set(all_ids)))

assert len(all_ids) == len(set(all_ids)), "Duplicate IDs found!"
assert len(all_ids) == all_embeddings.shape[0], "Mismatch between IDs and embeddings!"

"""### Write into a master file"""

CSV_PATH = "cxr_embeddings.h5"
with h5py.File(CSV_PATH, "w") as hdf:
    grp = hdf.create_group("cxr_embeddings")

    str_dtype = h5py.string_dtype(encoding='utf-8')

    grp.create_dataset(
        "dicom_ids",
        data=np.array(all_ids, dtype=str_dtype)
    )

    grp.create_dataset(
        "embeddings",
        data=all_embeddings,
        compression="gzip"
    )

    grp.attrs["embedding_dim"] = all_embeddings.shape[1]
    grp.attrs["total_samples"] = all_embeddings.shape[0]
    grp.attrs["source_files"] = ",".join(FILES)

print("Saved cxr_embeddings.h5 successfully.")

from google.colab import files

files.download(CSV_PATH)