# Generated by Django 6.0.2 on 2026-03-27 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_remove_visit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='admit_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
