# Generated by Django 6.0.2 on 2026-03-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(blank=True, max_length=6, unique=True)),
                ('assessments_used', models.JSONField(default=list, help_text='List of Assessment PKs whose windows were used to compute this result.')),
                ('severity_index', models.IntegerField(default=1, help_text='n in S_n — number of 4-hour windows used for this inference run.')),
                ('inference_id', models.UUIDField(blank=True, default=None, help_text='UUID generated by the inference service for this result row.', null=True, unique=True)),
                ('severity_score', models.FloatField(default=0.0)),
                ('mortality_risk', models.FloatField(default=0.0)),
                ('vent_prob', models.FloatField(default=0.0)),
                ('dialysis_prob', models.FloatField(default=0.0)),
                ('mechanical_prob', models.FloatField(default=0.0)),
                ('cardiac_prob', models.FloatField(default=0.0)),
                ('global_sev_prob', models.FloatField(default=0.0)),
                ('assessment_report', models.TextField(default='')),
                ('is_stale', models.BooleanField(default=False, help_text='True when a source file deletion has invalidated this result. A new inference run will produce a fresh non-stale row.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.CharField(blank=True, max_length=6, unique=True)),
                ('window_id', models.IntegerField(help_text='1-6, representing the 4-hour window index from admission')),
                ('time_window_start', models.DateTimeField()),
                ('time_window_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('visit', 'window_id')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assessment/')),
                ('file_type_label', models.CharField(blank=True, default='', help_text='e.g., PA, AP, LL for CXR; AR, RR for reports', max_length=20)),
                ('data_category', models.CharField(choices=[('radiography_image', 'Radiography Image'), ('clinical_notes', 'Clinical Notes'), ('vitals', 'Vitals'), ('labs', 'Labs')], max_length=30)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_applicable', 'N/A')], default='not_applicable', max_length=20)),
                ('aggregation_status', models.CharField(choices=[('pending', 'Pending'), ('aggregated', 'Aggregated'), ('failed', 'Failed')], default='pending', help_text="Tracks whether this file's data has been incorporated into window_store.h5. Reset to 'pending' when the file is part of a window that needs re-aggregation.", max_length=20)),
                ('charttime', models.DateTimeField(blank=True, db_index=True, help_text='Actual time the measurement or image was taken.', null=True)),
                ('window_id', models.IntegerField(blank=True, null=True)),
                ('t_global', models.FloatField(blank=True, null=True)),
                ('t_window', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assessments.assessment')),
            ],
            options={
                'ordering': ['charttime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_id', models.IntegerField(help_text='1-6, the 4-hour window these measurements belong to.')),
                ('measurements', models.JSONField(default=list, help_text='Array of normalised lab events. Each event: {lab_type, lab_value, t_global, t_window}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(help_text='The AssessmentFile whose PDF produced these measurements.', on_delete=django.db.models.deletion.CASCADE, related_name='lab_measurements', to='assessments.assessmentfile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_measurements', to='visits.visit')),
            ],
            options={
                'ordering': ['window_id'],
                'unique_together': {('source_file', 'visit', 'window_id')},
            },
        ),
        migrations.CreateModel(
            name='VitalMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_id', models.IntegerField(help_text='1-6, the 4-hour window these measurements belong to.')),
                ('measurements', models.JSONField(default=list, help_text='Array of normalised vital snapshots. Each event: {vital_type, vital_mean, vital_std, vital_last, vital_count, t_global, t_window}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(help_text='The AssessmentFile whose PDF produced these measurements.', on_delete=django.db.models.deletion.CASCADE, related_name='vital_measurements', to='assessments.assessmentfile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_measurements', to='visits.visit')),
            ],
            options={
                'ordering': ['window_id'],
                'unique_together': {('source_file', 'visit', 'window_id')},
            },
        ),
    ]
