# Generated by Django 6.0.2 on 2026-03-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='visit',
            field=models.ForeignKey(blank=True, help_text='The patient visit this inference result belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='visits.visit'),
        ),
        migrations.AlterField(
            model_name='labmeasurement',
            name='source_file',
            field=models.ForeignKey(blank=True, help_text='The assessment file (Labs PDF/CSV) that provided this measurement.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_measurements', to='assessments.assessmentfile'),
        ),
        migrations.AlterField(
            model_name='vitalmeasurement',
            name='source_file',
            field=models.ForeignKey(blank=True, help_text='The assessment file (Vitals PDF/CSV) that provided this measurement.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_measurements', to='assessments.assessmentfile'),
        ),
    ]
