# Generated by Django 6.0.2 on 2026-03-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentfile',
            name='t_global',
        ),
        migrations.RemoveField(
            model_name='assessmentfile',
            name='t_window',
        ),
        migrations.RemoveField(
            model_name='assessmentfile',
            name='window_id',
        ),
    ]
